timeout 20

use_nvram false

scanfor manual

#menuentry "Arch Linux" {
#    icon     /EFI/refind/icons/os_arch.png
#    loader   /EFI/Arch/vmlinuz-linux
#    initrd   /EFI/Arch/initramfs-linux.img
#    options  "root=PARTUUID=7f56f446-ccca-4b10-8b0b-585920d46dce rw add_efi_memmap"
#    submenuentry "Boot using fallback initramfs" {
#        initrd /EFI/Arch/initramfs-linux-fallback.img
#    }
#    submenuentry "Boot to terminal" {
#        add_options "systemd.unit=multi-user.target"
#    }
#}

#menuentry "Nix Os" {
#    loader /EFI/NixOs/vmlinuz-linux
#    initrd /EFI/NixOs/initramfs-linux.img 
#    options "systemConfig=/nix/var/nix/profiles/system-3-link \
#             init=/nix/store/d67r6yxjrnqqrssh00x5gwxciqyk6vns-initrd-linix-6.12.30/initrd"
#}

menuentry "Windows 10" {
		#icon /EFI/refind/icons/os_win.png
		icon /EFI/refind/icons/os_win8.png
    loader /EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry "Nix Os systemd-boot" {
		icon /EFI/refind/icons/os_nix.png
    loader /EFI/systemd/systemd-bootx64.efi
    graphics on
}

menuentry "Memtest86+" {
    loader /EFI/tools/memtest.efi
}

include theme.conf
